spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank

keycloak:
  realm: bank
  auth-server-url: http://keycloak:8080
  resource: bank-auth-server