server:
  port: 8081

spring:
  application:
    name: bank-accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm
  cloud:
    gateway:
      routes:
        - id: bank-accounts
          uri: lb://bank-accounts
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka