server:
  port: 8091

spring:
  application:
    name: bank-blocker
  cloud:
    config:
      uri: http://config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka