spring:
  application:
    name: bank-gateway
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: http://bank-accounts:8080
          predicates:
            - Path=/api/accounts/**
          filters:
            - TokenRelay
      default-filters:
        - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm
      client:
        registration:
          keycloak:
            client-id: bank-gateway
            client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka