server:
  port: 8090
spring:
  application:
    name: bank-transfer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bank-auth-server:8080/realms/bank-realm

eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka